adding checking version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,5 +18,7 @@ jobs:
         with:
           go-version: "1.25.1"
 
-      - name: Force Failure
-        run: (exit 1)
+      - name: check version
+        run: go version
+      # - name: Force Failure
+      #   run: (exit 1)
